// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9GG27C32LDE4B2Nk40OchnJFX6FLNCzA',
    appId: '1:722126546862:web:603674e16f5fdc04278a3f',
    messagingSenderId: '722126546862',
    projectId: 'hazir-app',
    authDomain: 'hazir-app.firebaseapp.com',
    databaseURL: 'https://hazir-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hazir-app.appspot.com',
    measurementId: 'G-B329J9M9K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCkJ_Imcx_Qw4_SLSJMDDvTIKTwUk4xs',
    appId: '1:722126546862:android:6f4558ff51e64f8b278a3f',
    messagingSenderId: '722126546862',
    projectId: 'hazir-app',
    databaseURL: 'https://hazir-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hazir-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhetvpoBSUWQ9v4bMux5kn2JJDd9v60k',
    appId: '1:722126546862:ios:fe9bb313df43e8c1278a3f',
    messagingSenderId: '722126546862',
    projectId: 'hazir-app',
    databaseURL: 'https://hazir-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hazir-app.appspot.com',
    iosClientId: '722126546862-mb9em1pnu94qikovr0bspl2goqr73dj9.apps.googleusercontent.com',
    iosBundleId: 'com.habib.hazirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhetvpoBSUWQ9v4bMux5kn2JJDd9v60k',
    appId: '1:722126546862:ios:fe9bb313df43e8c1278a3f',
    messagingSenderId: '722126546862',
    projectId: 'hazir-app',
    databaseURL: 'https://hazir-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hazir-app.appspot.com',
    iosClientId: '722126546862-mb9em1pnu94qikovr0bspl2goqr73dj9.apps.googleusercontent.com',
    iosBundleId: 'com.habib.hazirApp',
  );
}
